Login page
duumbling/e-commerce-application pull request #100
Opened 2023-08-15 16:38 UTC by duumbling

## Описание изменений 📝

Добавил форму, стили и ссылку на страницу регистрации для страницы логина

## Тип изменений 📚

Новая функциональность

## Проверка изменений 🔍

Попробовать перейти на страницу логина

## Особые замечания для вашего рецензента ❗

Страница пока что без функционала входа, данные формы пока что выводятся в консоль

## Скриншот 📷
![image](https://github.com/duumbling/e-commerce-application/assets/123836489/cbf27867-f574-4b9a-bfd0-c9957de99e4f)

2023-08-16 04:29 UTC, roshik14 requested changes

2023-08-16 04:29 UTC, roshik14 commented on src/pages/login/ui/style.ts
> +  md: 4,
Можно `...gridItemProps`

2023-08-16 04:29 UTC, roshik14 commented on src/widgets/login-form/ui/LoginForm.tsx
> +  }
Немного непривычно видеть объявление интерфейса внутри компонента

2023-08-16 04:29 UTC, roshik14 commented on src/widgets/login-form/ui/LoginForm.tsx
> +                href="/register"
Используй enum Paths и ссылку из shared

2023-08-16 05:14 UTC, duumbling commented on src/pages/login/ui/style.ts
> +  md: 4,
![image](https://github.com/duumbling/e-commerce-application/assets/123836489/14ee9519-a611-4af1-955e-900ddbb8c8f7)
Так?

2023-08-16 05:17 UTC, duumbling commented on src/widgets/login-form/ui/LoginForm.tsx
> +  }
Лучше вынести в model -> types как в форме регистрации?

2023-08-16 05:22 UTC, duumbling commented on src/widgets/login-form/ui/LoginForm.tsx
> +                href="/register"
fixed

2023-08-16 05:24 UTC, roshik14 commented on src/widgets/login-form/ui/LoginForm.tsx
> +  }
Можно просто перед компонентом (выше)

2023-08-16 05:26 UTC, roshik14 commented on src/pages/login/ui/style.ts
> +  md: 4,
Ну да, можно и так, либо в объекте gridHeaderProps внутри написать `...gridItemProps`

2023-08-16 05:36 UTC, duumbling commented on src/widgets/login-form/ui/LoginForm.tsx
> +  }
fixed

2023-08-16 05:36 UTC, duumbling commented on src/pages/login/ui/style.ts
> +  md: 4,
fixed

2023-08-16 05:41 UTC, roshik14 requested changes

2023-08-16 05:41 UTC, roshik14 commented on src/widgets/login-form/ui/LoginForm.tsx
> +                href={Paths.Main}
На страницу регистрации)

2023-08-16 17:01 UTC, duumbling commented on src/widgets/login-form/ui/LoginForm.tsx
> +                href={Paths.Main}
fixed

2023-08-16 18:33 UTC, SkarabeyDM requested changes

2023-08-16 18:33 UTC, SkarabeyDM commented on src/widgets/login-form/ui/style.ts
> +  },
Это лишнее, т.к. перекроет имеющийся эффект наведения
```suggestion
```

2023-08-16 18:33 UTC, SkarabeyDM commented on src/widgets/login-form/ui/LoginForm.tsx
>                </Link>
Не тот компонент ссылки. Используй тот, что в `shared/ui/Link`. Цвет менять не надо, он по умолчанию чёрный.
```suggestion
              <Link
                href={Paths.Register}
                sx={linkStyle}
              >
                Нет аккаунта? Зарегистрироваться
              </Link>
```

2023-08-16 18:35 UTC, SkarabeyDM commented
В папке страницы есть два компонента `LoginPage` - удали один

2023-08-16 19:11 UTC, duumbling commented on src/widgets/login-form/ui/LoginForm.tsx
>                </Link>
fixed

2023-08-16 19:11 UTC, duumbling commented on src/widgets/login-form/ui/style.ts
> +  },
fixed

2023-08-16 20:00 UTC, SkarabeyDM approved these changes

2023-08-17 01:16 UTC, roshik14 approved these changes

2023-08-17 04:49 UTC, merged