Change props types
duumbling/e-commerce-application pull request #129
Opened 2023-08-16 18:39 UTC by duumbling

## Описание изменений 📝

Изменил типы пропсов

## Тип изменений 📚

Новая функциональность

## Проверка изменений 🔍

Попробовать передать пропсы в кастомный свич

## Обоснование изменений 💡

Старый тип пропсов не позволял принимать пропсы так, как это требуется

2023-08-16 18:44 UTC, SkarabeyDM commented
Это @roshik14  заказывал, если не ошибаюсь, и он же будет проверять. Поэтому аппрувну, чтоб не замедлять проверку

2023-08-16 18:45 UTC, SkarabeyDM approved these changes

2023-08-17 01:17 UTC, roshik14 approved these changes

2023-08-17 01:18 UTC, roshik14 requested changes
Поменяй export default на export function CustomSwitch

2023-08-17 05:14 UTC, Limhill approved these changes

2023-08-19 00:35 UTC, roshik14 approved these changes

2023-08-19 00:45 UTC, merged