Login authorization
duumbling/e-commerce-application pull request #130
Opened 2023-08-16 21:22 UTC by duumbling

## Описание изменений 📝

Добавил авторизацию пользователя, отображение ошибки, если пользователь не найден и редирект на главную, если авторизация успешна

## Тип изменений 📚

Новая функциональность

## Проверка изменений 🔍

Попробуйте авторизоваться

2023-08-17 02:04 UTC, roshik14 requested changes

2023-08-17 02:04 UTC, roshik14 commented on src/widgets/login-form/lib/helpers.ts
> +export const isLoginError = (obj: Error): obj is RegistrationError =>
Функция называется isLoginError а проверяется на тип RegistrationError

2023-08-17 02:04 UTC, roshik14 commented on src/widgets/login-form/lib/helpers.ts
> +      "Customer account with the given credentials not found."
Лучше проверять на тип или код ошибки, в данном случае есть свойство code https://docs.commercetools.com/api/errors#ctp:api:type:InvalidCredentialsError

2023-08-17 02:04 UTC, roshik14 commented on src/pages/login/ui/LoginPage.tsx
> +    <div>
Лишний див

2023-08-17 04:52 UTC, duumbling commented on src/widgets/login-form/lib/helpers.ts
> +export const isLoginError = (obj: Error): obj is RegistrationError =>
Мы можем изменить название типа на FormError?
Потому что он подходит, вроде бы, и для логина

2023-08-17 04:52 UTC, duumbling commented on src/widgets/login-form/lib/helpers.ts
> +      "Customer account with the given credentials not found."
Пробовал сделать по коду, но тот код ошибки, которая прилетает, не нашёл

2023-08-17 05:02 UTC, roshik14 commented on src/widgets/login-form/lib/helpers.ts
> +export const isLoginError = (obj: Error): obj is RegistrationError =>
думаю да, можно

2023-08-17 05:13 UTC, Limhill commented on src/widgets/login-form/lib/helpers.ts
> +  "body" in obj;
Подумайте над тем, чтобы заменять in на Object.hasOwnProperty

2023-08-17 05:14 UTC, Limhill approved these changes

2023-08-17 05:23 UTC, roshik14 commented on src/widgets/login-form/lib/helpers.ts
> +      "Customer account with the given credentials not found."
Тогда ок

2023-08-18 20:48 UTC, duumbling commented on src/widgets/login-form/lib/helpers.ts
> +export const isLoginError = (obj: Error): obj is RegistrationError =>
fixed

2023-08-18 20:50 UTC, duumbling commented on src/pages/login/ui/LoginPage.tsx
> +    <div>
fixed

2023-08-18 20:50 UTC, duumbling commented on src/widgets/login-form/lib/helpers.ts
> +  "body" in obj;
fixed

2023-08-19 00:34 UTC, roshik14 approved these changes

2023-08-19 00:45 UTC, merged