`Footer`
duumbling/e-commerce-application pull request #151
Opened 2023-08-27 11:53 UTC by SkarabeyDM

## Описание изменений 📝

Добавил футер.

## Тип изменений 📚

Новая функциональность

## Проверка изменений 🔍

Запустить сборку, футер уже добавлен в компонент `Layout`

## Скриншот 📷

![image](https://github.com/duumbling/e-commerce-application/assets/46022177/d9817715-e8fa-4a9a-97f1-5097aaae577d)

2023-08-28 04:04 UTC, roshik14 requested changes

2023-08-28 04:04 UTC, roshik14 commented on src/shared/lib/helpers/styles/styles.ts
> +export type SX = SxProps<Theme>;
Если этот тип нигде не используется, значит он не нужен

2023-08-28 04:04 UTC, roshik14 commented on src/shared/lib/helpers/styles/styles.ts
> +}
1. Если это обычная функция (не компонент), следует писать через `const = () =>` и указывать возвращаемый тип
2. Мне кажется, что можно дать функции понятное название, отвечающее на вопрос "что она делает", тогда комментарий будет не нужен

2023-08-28 04:04 UTC, roshik14 commented on src/shared/lib/helpers/styles/styles.ts
> +    return Object.assign(resolvedSx as object, sx);
Вместо `if (sx === undefined)`, в данном случае можно использовать оператор `??`

2023-08-28 10:50 UTC, SkarabeyDM commented on src/shared/lib/helpers/styles/styles.ts
> +}
Исправил

2023-08-28 10:50 UTC, SkarabeyDM commented on src/shared/lib/helpers/styles/styles.ts
> +export type SX = SxProps<Theme>;
Исправил

2023-08-28 10:51 UTC, SkarabeyDM commented on src/shared/lib/helpers/styles/styles.ts
> +    return Object.assign(resolvedSx as object, sx);
Исправил

2023-08-28 13:09 UTC, Limhill approved these changes

2023-08-29 09:20 UTC, roshik14 approved these changes

2023-08-29 10:07 UTC, merged