Products search
duumbling/e-commerce-application pull request #156
Opened 2023-08-30 11:41 UTC by roshik14

## Описание изменений 📝

<details>Добавил строку поиска товаров и компонент CategoryProductsWidget</details>

## Тип изменений 📚

<details>Новая функциональность</details>

## Проверка изменений 🔍

<details>Открыть страницу каталога и попробовать ввести в поиск слова</details>

## Особые замечания для вашего рецензента ❗

<details>
Есть небольшая проблема с тем, что апишка разделяет текст запроса на слова и ищет по ним совпадения, поэтому если искать например "Кроссовки женские", то вернутся также и мужские, потому что это тоже "Кроссовки"
</details>

## Скриншот 📷
![image](https://github.com/duumbling/e-commerce-application/assets/75363608/a25f0f38-c90f-451c-9ba3-9e3bf32ce9f7)

2023-08-31 10:35 UTC, SkarabeyDM approved these changes

2023-08-31 13:53 UTC, Limhill requested changes

2023-08-31 13:53 UTC, Limhill commented on src/features/ProductCardsView/model/hooks.ts
>    const [isLoading, setIsLoading] = useState(true);
надо переименовать

2023-08-31 13:53 UTC, Limhill commented on src/entities/products-search/model/hooks.ts
> +    const timer = setTimeout(() => {
нужно юзать либо библиотечный debounce, либо вынести свой кастомный в shared

2023-09-01 00:44 UTC, roshik14 commented on src/features/ProductCardsView/model/hooks.ts
>    const [isLoading, setIsLoading] = useState(true);
fixed

2023-09-01 00:44 UTC, roshik14 commented on src/entities/products-search/model/hooks.ts
> +    const timer = setTimeout(() => {
исправил на debounce из lodash

2023-09-01 05:54 UTC, Limhill approved these changes

2023-09-01 06:01 UTC, merged