Product page
duumbling/e-commerce-application pull request #163
Opened 2023-09-03 11:50 UTC by SkarabeyDM

## Описание изменений 📝

Сделал черновой вариант страницы продукта

## Тип изменений 📚

Новая функциональность

## Проверка изменений 🔍

Пройти по ссылке `/product`

## Скриншот 📷

![image](https://github.com/duumbling/e-commerce-application/assets/46022177/15e02639-818f-430a-b001-aa67adc8d7d7)

2023-09-03 11:58 UTC, roshik14 approved these changes

2023-09-03 13:12 UTC, Limhill requested changes

2023-09-03 13:12 UTC, Limhill commented on src/app/routes/AppRoutes.tsx
> +// TODO Изменить роутинг на страницу продукта
Лучше добавлять ещё "когда нужно внести изменения"

2023-09-03 13:12 UTC, Limhill commented on src/pages/detailedProduct/DetailedProductPage.tsx
> +                {["#ffffff", "#000000", "#ff00ff"].map((color) => {
Цвета наверное лучше вынести отдельно. Иначе непонятно почему именно этот набор и в почему именно в такой последовательности

2023-09-03 13:12 UTC, Limhill commented on src/pages/detailedProduct/DetailedProductPage.tsx
> +                            outlineOffset: "-.5rem",
```suggestion
                            outlineOffset: "-0.5rem",
```

2023-09-03 13:12 UTC, Limhill commented on src/pages/detailedProduct/DetailedProductPage.tsx
> +                {[38, 40, 41].map((size) => {
тоже не совсем понятно что это за числа и почему именно такие

2023-09-03 13:12 UTC, Limhill commented on src/shared/ui/FavoriteButton/ui/style.ts
> +    p: ".25rem",
```suggestion
    p: "0.25rem",
```

2023-09-03 21:16 UTC, SkarabeyDM commented on src/shared/ui/FavoriteButton/ui/style.ts
> +    p: ".25rem",
Исправил

2023-09-03 21:18 UTC, SkarabeyDM commented on src/pages/detailedProduct/DetailedProductPage.tsx
> +                {[38, 40, 41].map((size) => {
Вынес в отдельную переменную

2023-09-03 21:18 UTC, SkarabeyDM commented on src/pages/detailedProduct/DetailedProductPage.tsx
> +                {["#ffffff", "#000000", "#ff00ff"].map((color) => {
Вынес в отдельную переменную

2023-09-03 21:19 UTC, SkarabeyDM commented on src/app/routes/AppRoutes.tsx
> +// TODO Изменить роутинг на страницу продукта
Добавил условие

2023-09-03 21:19 UTC, SkarabeyDM commented on src/pages/detailedProduct/DetailedProductPage.tsx
> +                            outlineOffset: "-.5rem",
Исправил

2023-09-04 01:45 UTC, Limhill approved these changes

2023-09-04 05:45 UTC, merged