Detailed team description
duumbling/e-commerce-application pull request #217
Opened 2023-09-07 13:28 UTC by duumbling

## Описание изменений 📝

Добавил наполнение страницы About us

## Тип изменений 📚

новая функциональность

## Особые замечания для вашего рецензента ❗

Информацию и актуальные фото добавлю позже

## Скриншот 📷
![image](https://github.com/duumbling/e-commerce-application/assets/123836489/51877b7e-c452-43e2-9fab-bfc170158083)
![image](https://github.com/duumbling/e-commerce-application/assets/123836489/491da07f-831e-4458-9736-2371c1314bc8)

2023-09-08 02:13 UTC, roshik14 requested changes

2023-09-08 02:13 UTC, roshik14 commented on src/features/AboutUsItem/ui/AboutUsItem.tsx
> +  const otherWords = words.slice(1).join(" ");
Мне кажется тут можно было мемоизировать (придирка)

2023-09-08 02:13 UTC, roshik14 commented on src/pages/about/ui/AboutPage.tsx
> +    <Box>
Если просто нужен враппер, то мне кажется, что в таких случаях лучше использовать React.Fragment (придирка)

https://react.dev/reference/react/Fragment

2023-09-08 02:13 UTC, roshik14 commented on src/pages/about/ui/AboutPage.tsx
> +            <Typography variant="h4" sx={{ ...titleStyle }}>
В `sx` можно передать сам объект `titleStyle`, без деструктуризации (придирка)

2023-09-08 02:13 UTC, roshik14 commented on src/shared/developers-bio/Rashid/bio.ts
> +  "Рашид крутой а ещё тут есть много текста Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent augue lectus, aliquet at dignissim rhoncus, rhoncus vel erat. Integer ac posuere mauris,
а это точно должно быть в shared слое?

2023-09-08 03:18 UTC, Limhill commented on src/pages/about/ui/AboutPage.tsx
> +            <Typography variant="h4" sx={{ ...titleStyle }}>
Это очень здоровое замечание бтв

2023-09-08 03:19 UTC, Limhill commented on src/shared/developers-bio/Rashid/bio.ts
> +  "Рашид крутой а ещё тут есть много текста Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent augue lectus, aliquet at dignissim rhoncus, rhoncus vel erat. Integer ac posuere mauris,
Этому место вообще в assets где-то, явно не в исходном коде приложения

2023-09-12 07:46 UTC, roshik14 commented on src/pages/about/ui/AboutPage.tsx
> +    <Box>
fixed

2023-09-12 07:46 UTC, roshik14 commented on src/shared/developers-bio/Rashid/bio.ts
> +  "Рашид крутой а ещё тут есть много текста Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent augue lectus, aliquet at dignissim rhoncus, rhoncus vel erat. Integer ac posuere mauris,
переместил в assets

2023-09-14 14:12 UTC, SkarabeyDM approved these changes

2023-09-14 14:51 UTC, Limhill approved these changes

2023-09-15 00:49 UTC, roshik14 approved these changes

2023-09-15 00:49 UTC, merged