Registration from submit
duumbling/e-commerce-application pull request #93
Opened 2023-08-12 03:28 UTC by roshik14

## Описание изменений 📝

<details>Добавил создание кастомера</details>

## Тип изменений 📚

<details>Новая функциональность</details>

## Проверка изменений 🔍

<details>Заполнить данные и нажать кнопку зарегистрироваться, в консоли будет результат запроса</details>

## Особые замечания для вашего рецензента ❗

<details>
Пришлось испольовать forwardRef, чтобы в консоли не было ворнингов<br>
Добавил в AddressForm компонент автокомплит для стран, так как commercetools api принимает только код страны<br>
Пришлось использовать <code> as </code> для того чтобы в компонент AddressForm передавать контрол
</details>

## Скриншот 📷

2023-08-12 08:09 UTC, SkarabeyDM commented
Ошибки вылезают:
![image](https://github.com/duumbling/e-commerce-application/assets/46022177/c0682a98-e592-4f23-b657-0db8e7611be7)

2023-08-12 08:17 UTC, SkarabeyDM commented
Ошибки:
![image](https://github.com/duumbling/e-commerce-application/assets/46022177/c0682a98-e592-4f23-b657-0db8e7611be7)

2023-08-12 08:24 UTC, roshik14 commented
> Ошибки: ![image](https://user-images.githubusercontent.com/46022177/260212861-c0682a98-e592-4f23-b657-0db8e7611be7.png)

Исправил

2023-08-12 08:35 UTC, Limhill commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +  dateOfBirth: string;
Обычно стараются называть поля/переменные так, чтобы обходиться без of.

то есть здесь userBirthday

2023-08-12 08:37 UTC, Limhill commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +      console.log(res);
зачем этот console.log в проде?

2023-08-12 08:38 UTC, Limhill commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +  const addressFormControl = control as unknown as Control<AddressFormValues>;
вроде бы можно напрямую скастовать тип, без приведения к unknown

2023-08-12 08:45 UTC, Limhill requested changes

2023-08-12 08:45 UTC, Limhill commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +      console.log(res);
зачем этот console.log в проде?

2023-08-12 08:45 UTC, Limhill commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +  const addressFormControl = control as unknown as Control<AddressFormValues>;
вроде бы можно напрямую скастовать тип, без приведения к unknown

2023-08-12 14:17 UTC, duumbling approved these changes

2023-08-12 16:32 UTC, roshik14 commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +  dateOfBirth: string;
Исправил

2023-08-12 16:33 UTC, roshik14 commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +      console.log(res);
Исправил

2023-08-12 16:33 UTC, roshik14 commented on src/widgets/registration-form/ui/RegistrationForm.tsx
> +  const addressFormControl = control as unknown as Control<AddressFormValues>;
тайпскрипт ругается без приведения к unknown

2023-08-13 11:26 UTC, SkarabeyDM approved these changes

2023-08-13 12:05 UTC, Limhill approved these changes

2023-08-13 12:07 UTC, merged